# Generated by Django 5.1 on 2024-09-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_cosmetics_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetics',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
