# Generated by Django 5.1 on 2024-09-04 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_cosmetics_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ask',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='commentask',
            options={'verbose_name': 'answer', 'verbose_name_plural': 'answers'},
        ),
        migrations.RemoveField(
            model_name='cosmetics',
            name='user',
        ),
        migrations.AddField(
            model_name='ask',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='homepage.cosmetics'),
            preserve_default=False,
        ),
    ]
